apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-python.fullname" . }}-vault-template
data:
  config.tmpl: |
    {{ printf "{{- with secret \"secret/data/app-python/config\" -}}" }}
    export APP_SECRET={{ printf "{{ .Data.data.app_secret }}" }}
    export APP_ENV={{ printf "{{ .Data.data.app_env }}" }}
    {{ printf "{{- end -}}" }}