- name: Remove old docker sources list
  file:
    path: "/etc/apt/sources.list.d/docker.list"
    state: absent

- name: Remove old docker GPG key
  file:
    path: "/etc/apt/keyrings/docker.asc"
    state: absent

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Add docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable'
    state: present
    filename: docker

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Verify Docker installation
  command: docker --version
  register: docker_version

- name: Show Docker version
  debug:
    var: docker_version.stdout
