- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x'

- name: Verify Docker Compose installation
  command: /usr/local/bin/docker-compose --version
  register: compose_version

- name: Show Docker Compose version
  debug:
    var: compose_version.stdout
