- name: Wipe Docker containers and related files
  block:
    - name: Stop and remove Docker containers
      command:
        cmd: docker-compose -f "{{ docker_compose_file }}" down
        chdir: "{{ app_dir }}"
      when: web_app_full_wipe | bool
      tags: wipe

    - name: Remove Docker images
      command:
        cmd: docker-compose -f "{{ docker_compose_file }}" rm -f
        chdir: "{{ app_dir }}"
      when: web_app_full_wipe | bool
      tags: wipe

    - name: Remove application directory
      file:
        path: "{{ app_dir }}"
        state: absent
      when: web_app_full_wipe | bool
      tags: wipe

    - name: Remove Docker Compose binary
      file:
        path: /usr/local/bin/docker-compose
        state: absent
      when: web_app_full_wipe | bool
      tags: wipe
  tags: wipe